[[Config]]
provider = "vagrant"
box = "bento/ubuntu-16.04"

[[Network]]
type = "forwarded_port"
guest = "3306"
host = "3306"

[[Network]]
type = "forwarded_port"
guest = "4000"
host = "4000"

[[Network]]
type = "private_network"
ip = "192.168.33.10"

[[Cookbooks]]
dir="cookbooks"
